export const LANGUAGES = ['en-US',
    'id-ID',
    'ms-MY',
    'ca-ES',
    'cs-CZ',
    'da-DK',
    'de-DE',
    'et-EE',
    'es-ES',
    'fil-PH',
    'fr-FR',
    'hr-HR',
    'it-IT',
    'hu-HU',
    'nl-HU',
    'no-NO',
    'pl-PL',
    'pt-BR',
    'ro-RO',
    'sl-SI',
    'sv-SE',
    'vi-VN',
    'tr-TR',
    'yo-NG',
    'el-GR',
    'bg-BG',
    'ru-RU',
    'uk-UA',
    'he-IL',
    'ar-SA',
    'ne-NP',
    'hi-IN',
    'as-IN',
    'bn-IN',
    'ta-IN',
    'lo-LA',
    'th-TH',
    'ko-KR',
    'ja-JP',
    'zh-CN',
    'af-ZA',
    'auto',
];

export const SUPPORTED_CURRENCIES = {
    USD: 'USD',
    CAD: 'CAD',
    EUR: 'EUR',
    AUD: 'AUD',
    MXN: 'MXN',
    GBP: 'GBP',
    JPY: 'JPY',
    CNY: 'CNY',
    RUB: 'RUB',
    UAH: 'UAH',
    CHF: 'CHF',
};


export const REFERRAL_TYPES = {
    REWARDS: 'rewards',
};

export const REFERRAL_STATUSES = {
    NOT_ACTIVATED: 'notActivated',
    ACTIVATED: 'activated',
    REJECTED: 'rejected',
};
